#!/bin/sh
# mail-engine/docker/opendkim/entrypoint.sh — sign mail that leaves through Postfix.
#
# The key files are the SAME ones the Node engine signs with (mail-engine/keys/<domain>.private,
# generated by `cli keygen`). One key, one selector, one DNS record — whichever door a message
# leaves by, the signature verifies against the same published record.
set -eu

MAIL_DOMAINS="${MAIL_DOMAINS:-edurankai.in}"
SELECTOR="${MAIL_DKIM_SELECTOR:-era1}"
KEYDIR=/etc/opendkim/keys

: > /etc/opendkim/KeyTable
: > /etc/opendkim/SigningTable
: > /etc/opendkim/TrustedHosts

# Only the hosts we control may have their mail signed by us. A signing milter that trusts the world
# signs anything that reaches it — which is the DKIM equivalent of an open relay.
cat >> /etc/opendkim/TrustedHosts <<EOF
127.0.0.1
::1
localhost
172.16.0.0/12
192.168.0.0/16
10.0.0.0/8
EOF

signable=0
for domain in $(echo "$MAIL_DOMAINS" | tr ',' ' '); do
  key="$KEYDIR/$domain.private"
  if [ ! -f "$key" ]; then
    # NOT FATAL, AND NOT SILENT. A missing key means mail for that domain goes out unsigned, which
    # is worth shouting about at boot — but refusing to start would take down signing for every
    # OTHER domain too, and an unsigned message still beats no message.
    echo "[opendkim] WARNING: no key for $domain at $key — mail from that domain will be UNSIGNED."
    echo "[opendkim]          generate one with: node --import tsx mail-engine/src/cli.ts keygen $domain"
    continue
  fi
  echo "$SELECTOR._domainkey.$domain $domain:$SELECTOR:$key" >> /etc/opendkim/KeyTable
  echo "*@$domain $SELECTOR._domainkey.$domain" >> /etc/opendkim/SigningTable
  echo "$domain" >> /etc/opendkim/TrustedHosts
  signable=$((signable + 1))
done

echo "[opendkim] signing $signable domain(s) with selector $SELECTOR"
exec opendkim -f -x /etc/opendkim/opendkim.conf
