#!/bin/sh
# mail-engine/docker/opendkim/entrypoint.sh — sign mail that leaves through Postfix.
#
# The key files are the SAME ones the Node engine signs with (mail-engine/keys/<domain>.private,
# generated by `cli keygen`). One key, one selector, one DNS record — whichever door a message
# leaves by, the signature verifies against the same published record.
set -eu

MAIL_DOMAINS="${MAIL_DOMAINS:-edurankai.in}"
SELECTOR="${MAIL_DKIM_SELECTOR:-era1}"
KEYDIR=/etc/opendkim/keys

: > /etc/opendkim/KeyTable
: > /etc/opendkim/SigningTable
: > /etc/opendkim/TrustedHosts

# Only the hosts we control may have their mail signed by us. A signing milter that trusts the world
# signs anything that reaches it — which is the DKIM equivalent of an open relay.
cat >> /etc/opendkim/TrustedHosts <<EOF
127.0.0.1
::1
localhost
172.16.0.0/12
192.168.0.0/16
10.0.0.0/8
EOF

signable=0
for domain in $(echo "$MAIL_DOMAINS" | tr ',' ' '); do
  key="$KEYDIR/$domain.private"
  if [ ! -f "$key" ]; then
    # NOT FATAL, AND NOT SILENT. A missing key means mail for that domain goes out unsigned, which
    # is worth shouting about at boot — but refusing to start would take down signing for every
    # OTHER domain too, and an unsigned message still beats no message.
    echo "[opendkim] WARNING: no key for $domain at $key — mail from that domain will be UNSIGNED."
    echo "[opendkim]          generate one with: node --import tsx mail-engine/src/cli.ts keygen $domain"
    continue
  fi
  echo "$SELECTOR._domainkey.$domain $domain:$SELECTOR:$key" >> /etc/opendkim/KeyTable
  echo "*@$domain $SELECTOR._domainkey.$domain" >> /etc/opendkim/SigningTable
  # LEADING DOT. opendkim matches a peer entry against the client's reverse-DNS name by walking
  # suffixes that include the dot — "mail.edurankai.in", then ".edurankai.in". A bare
  # "edurankai.in" matches only a client whose PTR is exactly that, i.e. nothing. The CIDR entries
  # above are what actually classify the compose network as internal; this makes the intent real
  # rather than decorative.
  echo ".$domain" >> /etc/opendkim/TrustedHosts
  signable=$((signable + 1))
done

# EVERY OPENDKIM DIAGNOSTIC WAS BEING DISCARDED. opendkim.conf sets `Syslog yes` and writes nothing
# to stderr, but an alpine image has no syslogd and no /dev/log — so "key data is not secure",
# "can't load key" and "no signing table match" all went to a socket that does not exist. `docker
# logs opendkim` showed two echo lines from this script and nothing else, and the success line was
# computed from a file-existence test. A signing milter that silently signs nothing is exactly the
# failure this stack cannot afford, because the mail still goes out — unsigned.
busybox syslogd -n -O /proc/1/fd/1 &

# Assert something real. `[ -f ]` proves a file exists; opendkim-testkey proves opendkim can parse
# the key and that it matches what is published in DNS. A DNS failure here is expected before the
# record is published, so it is reported, not fatal.
for domain in $(echo "$MAIL_DOMAINS" | tr ',' ' '); do
  [ -f "$KEYDIR/$domain.private" ] || continue
  if opendkim-testkey -d "$domain" -s "$SELECTOR" -k "$KEYDIR/$domain.private" 2>&1 | head -2; then :; fi
done

echo "[opendkim] signing $signable domain(s) with selector $SELECTOR"
exec opendkim -f -x /etc/opendkim/opendkim.conf
