// mail-engine/src/mime/dsn.ts — reading the bounces that come back hours later.
//
// THERE ARE TWO KINDS OF BOUNCE AND THIS ENGINE HAS TO HANDLE BOTH.
//
//   SYNCHRONOUS   The receiving server says 550 during the SMTP conversation. smtp/classify.ts
//                 handles that one, and it is the easy one: we are still holding the message.
//   ASYNCHRONOUS  The receiving server says 250, accepts responsibility, then discovers minutes or
//                 hours later that it cannot deliver, and mails a report back to the envelope
//                 sender. Large providers do this constantly, and a sender that ignores these
//                 reports has no idea which of its addresses are dead.
//
// This file is the second kind. RFC 3464 defines the format: a multipart/report whose
// message/delivery-status part holds one group of fields per recipient. RFC 5965 defines ARF, the
// abuse report format, which is what a provider sends when a recipient presses "this is spam" — and
// a spam complaint is a stronger signal than any bounce, because a human made it.
//
// PARSED FROM THE RAW TEXT, NOT FROM A PART TREE, ON PURPOSE. Delivery reports are generated by
// every MTA ever written and a good number of them are subtly malformed — wrong boundary, missing
// content-type, the status part inlined as text/plain. Scanning for the field groups directly finds
// the recipients in all of those cases; a strict tree walk finds them in the well-formed ones only,
// and a bounce report that fails to parse is an address that stays on the list forever.

import type { BounceClass } from '../contracts/index.js';
import { classifySmtpReply, parseEnhancedCode } from '../smtp/classify.js';

export interface DsnRecipient {
  recipient: string;
  /** 'failed' (permanent), 'delayed' (temporary), 'delivered', 'relayed', 'expanded'. */
  action: string;
  status: string | null;              // RFC 3463 code, e.g. "5.1.1"
  diagnosticCode: string | null;      // "smtp; 550 5.1.1 User unknown"
  remoteMta: string | null;
  outcome: 'delivered' | 'deferred' | 'bounced';
  bounceClass: BounceClass | null;
  smtpCode: number | null;
}

export interface DsnReport {
  kind: 'dsn' | 'arf' | 'unknown';
  reportingMta: string | null;
  /** Message-ID of the message that bounced, when the report quotes it. */
  originalMessageId: string | null;
  /** Envelope sender of the original message, when the report states it. */
  originalFrom: string | null;
  recipients: DsnRecipient[];
  /** ARF only: 'abuse', 'fraud', 'virus', 'other'. */
  feedbackType: string | null;
}

/** Unfold RFC 5322 continuation lines (a leading space or tab continues the previous line). */
function unfold(text: string): string[] {
  const lines = text.replace(/\r\n/g, '\n').split('\n');
  const out: string[] = [];
  for (const line of lines) {
    if (/^[ \t]/.test(line) && out.length) out[out.length - 1] += ' ' + line.trim();
    else out.push(line);
  }
  return out;
}

function fieldValue(lines: string[], name: string): string | null {
  const re = new RegExp(`^${name}\\s*:\\s*(.*)$`, 'i');
  for (const line of lines) {
    const m = re.exec(line);
    if (m) return m[1].trim();
  }
  return null;
}

/** `rfc822; user@example.com` and `RFC822;<user@example.com>` both mean the same address. */
export function parseAddressField(value: string | null): string | null {
  if (!value) return null;
  const afterType = value.includes(';') ? value.slice(value.indexOf(';') + 1) : value;
  const m = /[A-Za-z0-9._%+\-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+/.exec(afterType);
  return m ? m[0].toLowerCase() : null;
}

/** The SMTP reply quoted inside a Diagnostic-Code field, if there is one. */
export function parseDiagnosticCode(value: string | null): { smtpCode: number | null; text: string | null } {
  if (!value) return { smtpCode: null, text: null };
  const text = value.includes(';') ? value.slice(value.indexOf(';') + 1).trim() : value.trim();
  const m = /\b([245]\d{2})\b/.exec(text);
  return { smtpCode: m ? Number(m[1]) : null, text };
}

/**
 * Parse a delivery report. Returns recipients: [] when the message is not a report at all, which is
 * how the caller distinguishes "a bounce we could not read" from "ordinary mail".
 */
export function parseDsn(raw: Buffer | string): DsnReport {
  const text = Buffer.isBuffer(raw) ? raw.toString('utf8') : raw;
  const lines = unfold(text);

  const isArf = /content-type:\s*message\/feedback-report/i.test(text) || /^feedback-type\s*:/im.test(text);
  const reportingMta = fieldValue(lines, 'Reporting-MTA');
  const feedbackType = isArf ? fieldValue(lines, 'Feedback-Type') : null;

  // The bounced message's own Message-ID. In a DSN the original message is quoted in a
  // message/rfc822 part; in ARF it is quoted too, and the header may also appear as
  // `Original-Message-ID` or `Message-ID` inside the report body. The LAST match wins: the report's
  // own Message-ID comes first in the file, the quoted original comes after it.
  const idMatches = [...text.matchAll(/^(?:original-message-id|message-id)\s*:\s*(<[^>\r\n]+>)/gim)];
  const originalMessageId = idMatches.length ? idMatches[idMatches.length - 1][1] : null;
  const originalFrom = parseAddressField(fieldValue(lines, 'Original-Mail-From')) || parseAddressField(fieldValue(lines, 'X-Original-From'));

  const recipients: DsnRecipient[] = [];

  // Each recipient group starts at a Final-Recipient (or Original-Recipient) line and runs to the
  // next one, or to the end. Splitting on blank lines is not reliable — plenty of MTAs emit the
  // fields with no separating blank line at all.
  // Final-Recipient starts a group. Original-Recipient does NOT — it is an optional extra field
  // INSIDE a group, and treating it as a start splits every well-formed Postfix report in two: the
  // first half holds the address and the second holds the Action and Status, so the bounce arrives
  // with no reason attached. Only when a report omits Final-Recipient entirely does
  // Original-Recipient become the group marker.
  const startsWith = (re: RegExp) => lines.reduce<number[]>((acc, line, i) => {
    if (re.test(line)) acc.push(i);
    return acc;
  }, []);
  let indices = startsWith(/^final-recipient\s*:/i);
  if (!indices.length) indices = startsWith(/^original-recipient\s*:/i);

  for (let i = 0; i < indices.length; i++) {
    const start = indices[i];
    const end = i + 1 < indices.length ? indices[i + 1] : Math.min(lines.length, start + 25);
    const group = lines.slice(start, end);

    const recipient = parseAddressField(fieldValue(group, 'Final-Recipient') || fieldValue(group, 'Original-Recipient'));
    if (!recipient) continue;
    if (recipients.some((r) => r.recipient === recipient)) continue;

    const action = (fieldValue(group, 'Action') || '').toLowerCase() || 'failed';
    const status = fieldValue(group, 'Status');
    const diagnostic = fieldValue(group, 'Diagnostic-Code');
    const remoteMta = fieldValue(group, 'Remote-MTA');
    const diag = parseDiagnosticCode(diagnostic);

    // The Status field is authoritative about permanence; the diagnostic code adds the detail.
    const enhanced = status && /^[245]\.\d+\.\d+$/.test(status.trim()) ? status.trim() : parseEnhancedCode(diagnostic);
    let outcome: 'delivered' | 'deferred' | 'bounced';
    if (action === 'delivered' || action === 'relayed' || action === 'expanded') outcome = 'delivered';
    else if (action === 'delayed') outcome = 'deferred';
    else outcome = enhanced?.startsWith('4') ? 'deferred' : 'bounced';

    // Reuse the SMTP classifier so a bounce reported an hour later is classified by exactly the same
    // rules as one reported during the conversation. Two classifiers would drift within a month.
    const synthetic = [enhanced || '', diag.text || ''].filter(Boolean).join(' ');
    const cls = classifySmtpReply(diag.smtpCode ?? (outcome === 'bounced' ? 550 : outcome === 'deferred' ? 450 : 250), synthetic || null);

    recipients.push({
      recipient,
      action,
      status: enhanced,
      diagnosticCode: diag.text,
      remoteMta,
      outcome: outcome === 'delivered' ? 'delivered' : cls.outcome === 'delivered' ? outcome : cls.outcome,
      bounceClass: outcome === 'delivered' ? null : cls.bounceClass,
      smtpCode: diag.smtpCode,
    });
  }

  // An ARF report names its recipient in Original-Rcpt-To rather than in a Final-Recipient group.
  if (isArf && !recipients.length) {
    const rcpt = parseAddressField(fieldValue(lines, 'Original-Rcpt-To'));
    if (rcpt) {
      recipients.push({
        recipient: rcpt,
        action: 'failed',
        status: '5.7.1',
        diagnosticCode: `feedback-report; ${feedbackType || 'abuse'}`,
        remoteMta: reportingMta,
        // A COMPLAINT IS NOT A BOUNCE, AND IT IS TREATED AS MORE SERIOUS, NOT LESS. Somebody pressed
        // a button that says "this is spam". Mailing them again is how a sending domain gets blocked.
        outcome: 'bounced',
        bounceClass: 'spam_rejection',
        smtpCode: null,
      });
    }
  }

  return {
    kind: isArf ? 'arf' : recipients.length ? 'dsn' : 'unknown',
    reportingMta,
    originalMessageId,
    originalFrom,
    recipients,
    feedbackType,
  };
}
