#!/bin/sh
# mail-engine/docker/rspamd/entrypoint.sh
set -eu

REJECT="${RSPAMD_REJECT_SCORE:-15}"
QUARANTINE="${RSPAMD_QUARANTINE_SCORE:-6}"

# The thresholds are rendered from the environment so the SAME numbers drive rspamd's own actions and
# the engine's reading of the resulting headers. Two independently configured thresholds would
# eventually disagree, and the disagreement would look like mail vanishing.
cat > /etc/rspamd/local.d/actions.conf <<EOF
# Generated by entrypoint.sh from RSPAMD_REJECT_SCORE / RSPAMD_QUARANTINE_SCORE.
reject = ${REJECT};
add_header = ${QUARANTINE};
greylist = $(awk "BEGIN {print ${QUARANTINE} * 0.7}");
EOF

echo "[rspamd] reject at ${REJECT}, add-header at ${QUARANTINE}"
exec rspamd -f -u rspamd -g rspamd
