-- db/aquintutor-campus-schema.sql
--
-- ==================================================================================================
-- NINETEEN TABLES THAT EXISTED ONLY INSIDE PAGE FRONTMATTER
-- ==================================================================================================
--
-- CLAUDE.md tells anybody who needs the schema to READ THE SOURCE rather than open a connection:
-- src/lib/db/schema.ts, db/hr-schema.sql, and the admin page that writes a column. That instruction
-- could not be followed for any of these. Every one of them is created by a
-- `CREATE TABLE IF NOT EXISTS` inside the page or endpoint that happens to use it, at request time,
-- and none appeared in db/*.sql or in src/lib/db/schema.ts.
--
-- The practical effect: the only way to learn the shape of `counselling_requests` was to query
-- production — which is exactly the act that rule exists to prevent, and exactly how staff gender
-- data got read out of hr_employees on 2026-08-02.
--
-- So this file is the answer to that question, extracted from the source rather than from a database.
--
-- ==================================================================================================
-- WHAT THIS FILE IS AND IS NOT
-- ==================================================================================================
--
-- NOT a migration. Do not apply it. These tables already exist in production, created by the
-- statements below on their first request. Running it would be harmless (`IF NOT EXISTS`) and
-- pointless.
--
-- It IS the readable record of what those statements are, with the file that owns each one. When the
-- shape needs to change, change it at the source named under each heading; a copy edited only here
-- would be a second lie about the schema, which is the problem this documents.
--
-- ==================================================================================================
-- WHAT WAS CHECKED
-- ==================================================================================================
--
--   19 CREATE TABLE blocks, 19 distinct tables, across 17 files.
--   NO table is created in more than one place, so there is no divergent-definition problem — the
--   failure mode where two files create the same table with different columns and the first request
--   silently wins. That was the thing worth checking and it came back clean.
--
-- Generated by reading the source. Re-derive with the extractor described in
-- docs/aquintutor-audit/phase-1-discovery.md rather than by hand.


-- ------------------------------------------------------------------------------------------------
-- aq_feedback
-- owned by: src/pages/api/aquintutor/feedback.ts
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aq_feedback (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        page TEXT,
        lab TEXT,
        rating INT,
        comment TEXT,
        name TEXT,
        email TEXT,
        user_id UUID,
        user_agent TEXT,
        ip TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

-- ------------------------------------------------------------------------------------------------
-- buddy_requests
-- owned by: src/pages/aquintutor/campus/commons.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS buddy_requests (
      id BIGSERIAL PRIMARY KEY,
      full_name TEXT NOT NULL,
      email TEXT NOT NULL,
      year_of_study TEXT,
      buddy_kind TEXT,
      reason TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

-- ------------------------------------------------------------------------------------------------
-- club_joins
-- owned by: src/pages/aquintutor/campus/commons.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS club_joins (
      id BIGSERIAL PRIMARY KEY,
      club_slug TEXT NOT NULL,
      email TEXT NOT NULL,
      full_name TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

-- ------------------------------------------------------------------------------------------------
-- coffee_matches
-- owned by: src/pages/aquintutor/campus/commons.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS coffee_matches (
      id BIGSERIAL PRIMARY KEY,
      full_name TEXT NOT NULL,
      email TEXT NOT NULL,
      year_of_study TEXT,
      interests TEXT,
      preferred_time TEXT,
      match_date DATE,
      status TEXT DEFAULT 'pending',
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

-- ------------------------------------------------------------------------------------------------
-- counselling_requests
-- owned by: src/pages/aquintutor/campus/wellness.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS counselling_requests (
      id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      anonymous    boolean NOT NULL DEFAULT true,
      display_name text,
      contact      text,
      language     text NOT NULL DEFAULT 'English',
      topic        text,
      urgency      text NOT NULL DEFAULT 'standard',
      preferred_slot timestamptz,
      notes        text,
      status       text NOT NULL DEFAULT 'pending',
      created_at   timestamptz NOT NULL DEFAULT now()
    );

-- ------------------------------------------------------------------------------------------------
-- cultural_literacy_applications
-- owned by: src/pages/api/aquintutor/cultural/literacy-application.ts
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cultural_literacy_applications (
        id            BIGSERIAL PRIMARY KEY,
        full_name     TEXT NOT NULL,
        email         TEXT NOT NULL,
        year_of_study TEXT,
        track         TEXT,
        reason        TEXT,
        status        TEXT NOT NULL DEFAULT 'received',
        created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

-- ------------------------------------------------------------------------------------------------
-- daily_challenge_attempts
-- owned by: src/pages/api/aquintutor/daily-challenge.ts
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS daily_challenge_attempts (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      challenge_date DATE NOT NULL,
      questions_correct INTEGER NOT NULL DEFAULT 0,
      questions_attempted INTEGER NOT NULL DEFAULT 0,
      completed_at TIMESTAMPTZ,
      bonus_awarded BOOLEAN NOT NULL DEFAULT false,
      UNIQUE(user_id, challenge_date));

-- ------------------------------------------------------------------------------------------------
-- dorm_circle_signups
-- owned by: src/pages/aquintutor/campus/commons.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dorm_circle_signups (
      id BIGSERIAL PRIMARY KEY,
      full_name TEXT NOT NULL,
      email TEXT NOT NULL,
      year_of_study TEXT,
      circle_preference TEXT,
      availability TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

-- ------------------------------------------------------------------------------------------------
-- eir_applications
-- owned by: src/pages/aquintutor/incubation.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS eir_applications (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID, name VARCHAR(200), email VARCHAR(200),
        education TEXT, prior_work_url TEXT, prototype_url TEXT, idea_summary TEXT, target_market TEXT,
        plan_12mo TEXT, status VARCHAR(20) NOT NULL DEFAULT 'pending', created_at TIMESTAMPTZ DEFAULT NOW());

-- ------------------------------------------------------------------------------------------------
-- forge_bookings
-- owned by: src/pages/aquintutor/campus/forge.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS forge_bookings (
      id SERIAL PRIMARY KEY,
      equipment_id TEXT NOT NULL,
      equipment_name TEXT NOT NULL,
      user_email TEXT NOT NULL,
      user_handle TEXT,
      start_at TIMESTAMP NOT NULL,
      hours_requested NUMERIC(6,2) NOT NULL DEFAULT 1,
      file_url TEXT,
      file_kind TEXT,
      material TEXT,
      material_grams NUMERIC(8,2),
      ship_address TEXT,
      status TEXT NOT NULL DEFAULT 'queued',
      eta_at TIMESTAMP,
      operator_notes TEXT,
      audit_log JSONB DEFAULT '[]'::jsonb,
      created_at TIMESTAMP NOT NULL DEFAULT NOW()
    );

-- ------------------------------------------------------------------------------------------------
-- hall_bookings
-- owned by: src/pages/aquintutor/campus/halls.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hall_bookings (
      id SERIAL PRIMARY KEY,
      hall_id TEXT NOT NULL,
      organiser TEXT NOT NULL,
      booking_date DATE NOT NULL,
      slot TEXT NOT NULL,
      purpose TEXT NOT NULL,
      expected_attendance INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

-- ------------------------------------------------------------------------------------------------
-- library_ill_requests
-- owned by: src/pages/api/aquintutor/library/ill-request.ts
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS library_ill_requests (
        id            BIGSERIAL PRIMARY KEY,
        title         TEXT NOT NULL,
        author        TEXT,
        year          TEXT,
        publisher     TEXT,
        ident         TEXT,
        format        TEXT NOT NULL DEFAULT 'any',
        needed_by     DATE,
        reason        TEXT,
        requester_email TEXT NOT NULL,
        status        TEXT NOT NULL DEFAULT 'received',
        created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

-- ------------------------------------------------------------------------------------------------
-- partnership_applications
-- owned by: src/pages/aquintutor/partnerships.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS partnership_applications (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id UUID,
        partner_kind VARCHAR(40) NOT NULL DEFAULT 'institution',
          -- university | company | government | non-profit | individual-expert | publisher | media-house
        org_name VARCHAR(300) NOT NULL,
        contact_name VARCHAR(200),
        contact_email VARCHAR(200) NOT NULL,
        contact_phone VARCHAR(40),
        country VARCHAR(80),
        website_url TEXT,
        intended_course_title TEXT NOT NULL,
        intended_course_summary TEXT NOT NULL,
        target_learners TEXT,
        existing_content TEXT,
        co_branding TEXT,
        tier VARCHAR(20) NOT NULL DEFAULT 'starter',
          -- starter (one-off CHF 100) | scale (rev-share 15% per additional course)
        status VARCHAR(20) NOT NULL DEFAULT 'submitted',
          -- submitted | reviewing | approved | declined | onboarded
        signed_msa_at TIMESTAMPTZ,
        approved_at TIMESTAMPTZ,
        reviewer_notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

-- ------------------------------------------------------------------------------------------------
-- practice_problems
-- owned by: src/pages/aquintutor/practice.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS practice_problems (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      slug VARCHAR(200) UNIQUE,
      title TEXT,
      topic VARCHAR(80),
      difficulty VARCHAR(20),
      statement TEXT,
      constraints TEXT,
      sample_input TEXT,
      sample_output TEXT,
      starter_code JSONB,
      test_cases JSONB,
      solved_count INT DEFAULT 0,
      acceptance_pct INT,
      is_active BOOLEAN DEFAULT true,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

-- ------------------------------------------------------------------------------------------------
-- senior_placement_requests
-- owned by: src/pages/aquintutor/careerflow/placement.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS senior_placement_requests (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id UUID, name VARCHAR(200), email VARCHAR(200), years_experience INT,
        current_role VARCHAR(300), target_role VARCHAR(300), linkedin_url TEXT, cv_url TEXT,
        status VARCHAR(20) NOT NULL DEFAULT 'open', created_at TIMESTAMPTZ DEFAULT NOW());

-- ------------------------------------------------------------------------------------------------
-- sleep_program_signups
-- owned by: src/pages/aquintutor/campus/wellness.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sleep_program_signups (
      id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      display_name text,
      contact      text,
      timezone     text,
      chronotype   text,
      bedtime      text,
      waketime     text,
      goals        text,
      created_at   timestamptz NOT NULL DEFAULT now()
    );

-- ------------------------------------------------------------------------------------------------
-- srs_review_queue
-- owned by: src/pages/api/aquintutor/srs-review.ts
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS srs_review_queue (
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      question_id UUID NOT NULL,
      due_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      interval_days INTEGER NOT NULL DEFAULT 1,
      ease_factor NUMERIC(4,2) NOT NULL DEFAULT 2.5,
      repetitions INTEGER NOT NULL DEFAULT 0,
      last_seen_at TIMESTAMPTZ,
      PRIMARY KEY (user_id, question_id));

-- ------------------------------------------------------------------------------------------------
-- test_bookings
-- owned by: src/pages/aquintutor/campus/test-centres.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS test_bookings (
      id SERIAL PRIMARY KEY,
      test_id TEXT NOT NULL,
      test_name TEXT,
      candidate_name TEXT NOT NULL,
      candidate_email TEXT,
      slot TIMESTAMP NOT NULL,
      special_accommodations TEXT,
      tier TEXT DEFAULT 'standard',
      status TEXT DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT NOW()
    );

-- ------------------------------------------------------------------------------------------------
-- training_jobs
-- owned by: src/pages/aquintutor/labs/train.astro
-- ------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS training_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    job_name VARCHAR(200) NOT NULL,
    base_model VARCHAR(100),
    task_type VARCHAR(40),
    dataset_url TEXT,
    dataset_size INT,
    compute_target VARCHAR(40),
    hyperparams JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'queued',
    progress_pct INT DEFAULT 0,
    loss_curve JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
  );
