#!/usr/bin/env node
// scripts/typecheck-ratchet.mjs — a type check that can actually be enforced.
//
// THE PROBLEM WITH `tsc --noEmit` IN CI HERE: this repository does not currently type-check clean.
// There are pre-existing errors, in files nobody is touching, that predate the mail work. A CI job
// that runs tsc and fails is therefore red on every commit from the first day, which means it is
// disabled or ignored within a week — and then it catches nothing at all.
//
// SO THE GATE IS A RATCHET, NOT A CLIFF. The current errors are recorded per file in
// `.ci/typecheck-baseline.json`. A commit fails only if it makes things WORSE:
//   - a file that had no errors gains one, or
//   - a file's error count goes up.
// A commit that FIXES errors is reported, and the baseline should be regenerated in the same
// commit (`--update`) so the improvement is locked in and cannot silently regress.
//
// This is enforceable from the first day, it never blocks unrelated work, and the number can only
// go down. A clean `tsc` remains the goal; a red build nobody reads is not a step towards it.
//
//   node scripts/typecheck-ratchet.mjs            check against the baseline
//   node scripts/typecheck-ratchet.mjs --update   rewrite the baseline from the current state
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const BASELINE = join(ROOT, '.ci', 'typecheck-baseline.json');
const UPDATE = process.argv.includes('--update');

const tty = process.stdout.isTTY;
const paint = (c, s) => (tty ? `\x1b[${c}m${s}\x1b[0m` : s);
const red = (s) => paint('31', s);
const green = (s) => paint('32', s);
const yellow = (s) => paint('33', s);
const dim = (s) => paint('2', s);

process.stdout.write('\nRunning tsc --noEmit (this takes a couple of minutes on this repository)...\n');

let output = '';
try {
  output = execSync('npx tsc --noEmit -p tsconfig.json', { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 32 * 1024 * 1024 });
} catch (e) {
  // tsc exits non-zero when there are errors, which is the normal case here. The diagnostics are on
  // stdout, not stderr.
  output = `${e.stdout || ''}${e.stderr || ''}`;
}

/** `src/lib/foo.ts(12,5): error TS2345: ...` -> per-file counts. */
const counts = {};
for (const line of output.split(/\r?\n/)) {
  const m = /^(.+?)\(\d+,\d+\):\s+error\s+TS\d+:/.exec(line);
  if (!m) continue;
  const file = m[1].split('\\').join('/');
  counts[file] = (counts[file] || 0) + 1;
}
const total = Object.values(counts).reduce((a, b) => a + b, 0);

if (UPDATE) {
  mkdirSync(dirname(BASELINE), { recursive: true });
  writeFileSync(BASELINE, JSON.stringify({
    __comment: 'Pre-existing TypeScript errors, per file. Generated by scripts/typecheck-ratchet.mjs --update. This file exists so CI can fail on NEW type errors without being permanently red for old ones. When you fix errors, regenerate this in the same commit so the improvement is locked in.',
    generated: new Date().toISOString().slice(0, 10),
    total,
    files: counts,
  }, null, 2) + '\n');
  process.stdout.write(`${green('Baseline written')} — ${total} error(s) across ${Object.keys(counts).length} file(s)\n  ${dim(BASELINE)}\n\n`);
  process.exit(0);
}

if (!existsSync(BASELINE)) {
  process.stdout.write(`${yellow('No baseline recorded.')} Run:  node scripts/typecheck-ratchet.mjs --update\n\n`);
  process.exit(1);
}

const baseline = JSON.parse(readFileSync(BASELINE, 'utf8'));
const base = baseline.files || {};

const regressions = [];
const improvements = [];
for (const [file, count] of Object.entries(counts)) {
  const was = base[file] || 0;
  if (count > was) regressions.push({ file, was, now: count });
}
for (const [file, was] of Object.entries(base)) {
  const now = counts[file] || 0;
  if (now < was) improvements.push({ file, was, now });
}

process.stdout.write(`\n  baseline  ${baseline.total} error(s)  ${dim(`recorded ${baseline.generated}`)}\n`);
process.stdout.write(`  now       ${total} error(s)\n\n`);

if (improvements.length) {
  process.stdout.write(`${green('Improved:')}\n`);
  for (const i of improvements) process.stdout.write(`  ${i.file}  ${i.was} -> ${i.now}\n`);
  process.stdout.write(`  ${dim('Lock this in: node scripts/typecheck-ratchet.mjs --update, and commit .ci/typecheck-baseline.json')}\n\n`);
}

if (regressions.length) {
  process.stdout.write(`${red('NEW type errors:')}\n`);
  for (const r of regressions) process.stdout.write(`  ${r.file}  ${r.was} -> ${r.now}\n`);
  process.stdout.write('\n  The full diagnostics:\n');
  for (const line of output.split(/\r?\n/)) {
    if (regressions.some((r) => line.startsWith(r.file.split('/').join('\\')) || line.startsWith(r.file))) {
      process.stdout.write(`    ${line}\n`);
    }
  }
  process.stdout.write('\n');
  process.exit(1);
}

process.stdout.write(`${green('No new type errors.')}\n\n`);
process.exit(0);
